/**
 * Regenerates the two long tables on the company page (会社概要 and 沿革) from a
 * saved copy of that page. Both are dense, multi-line reference data where a
 * hand transcription would be easy to get subtly wrong.
 *
 *   node scripts/extract-company.mjs <mirror-root>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const [, , mirrorRoot = "."] = process.argv;

const html = readFileSync(join(mirrorRoot, "company", "index.html"), "utf8");

function toLines(fragment) {
  return fragment
    .replace(/<br\s*\/?>/g, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&#x([0-9a-f]+);/gi, (_, code) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
}

function tableAfter(heading) {
  const start = html.indexOf(heading);
  if (start === -1) throw new Error(`heading not found: ${heading}`);
  const table = html.slice(start).match(/<table>([\s\S]*?)<\/table>/);
  if (!table) throw new Error(`no table after: ${heading}`);
  return [...table[1].matchAll(/<tr>\s*<th>([\s\S]*?)<\/th>\s*<td>([\s\S]*?)<\/td>\s*<\/tr>/g)];
}

const profile = tableAfter("Company profile").map(([, th, td]) => ({
  label: toLines(th).join(" "),
  values: toLines(td)
}));

const history = tableAfter("History").map(([, th, td]) => {
  const era = th.match(/<em>([\s\S]*?)<\/em>/);
  const year = th.match(/<span>([\s\S]*?)<\/span>/);
  return {
    era: era ? toLines(era[1]).join(" ") : toLines(th).join(" "),
    year: year ? toLines(year[1]).join(" ") : "",
    body: toLines(td)
  };
});

const file = `// Generated by scripts/extract-company.mjs — edit that script, not this file.

/** A row of the 会社概要 table. */
export type ProfileRow = { label: string; values: string[] };

/** A row of the 沿革 table: Japanese era date, western year, and the entry. */
export type HistoryRow = { era: string; year: string; body: string[] };

export const companyProfile: ProfileRow[] = ${JSON.stringify(profile, null, 2)};

export const companyHistory: HistoryRow[] = ${JSON.stringify(history, null, 2)};
`;

writeFileSync(new URL("../data/company.ts", import.meta.url), file);
console.log(`data/company.ts: ${profile.length} profile rows, ${history.length} history rows`);
