/**
 * Regenerates data/privacy.ts from a saved copy of /privacy/.
 *
 * The privacy policy is a long, purely static legal document — it is kept as
 * markup so the wording and structure survive exactly.
 *
 *   node scripts/extract-privacy.mjs <mirror-root>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const [, , mirrorRoot = "."] = process.argv;

const html = readFileSync(join(mirrorRoot, "privacy", "index.html"), "utf8");

const start = html.indexOf('<div class="p-section__content">');
const end = html.indexOf("</section>", start);
if (start === -1 || end === -1) throw new Error("could not locate the policy body");

const body = html
  .slice(start + '<div class="p-section__content">'.length, end)
  .replace(/<!--[\s\S]*?-->/g, "")
  .replace(/https:\/\/www\.yahata-sa\.co\.jp\//g, "/")
  .replace(/\s*<\/div>\s*$/, "")
  .trim();

const file = `// Generated by scripts/extract-privacy.mjs — edit that script, not this file.
export const privacyBody = ${JSON.stringify(body)};
`;

writeFileSync(new URL("../data/privacy.ts", import.meta.url), file);
console.log(`data/privacy.ts: ${body.length} characters`);
