/**
 * Regenerates data/news.ts from saved copies of the WordPress news posts.
 *
 * The news posts are the only long-form, editor-authored pages on the site, so
 * their bodies are kept as HTML rather than being re-expressed as JSX. This
 * script normalises that HTML: absolute URLs become site-relative, responsive
 * `srcset` variants are dropped (only the size the editor picked is shipped),
 * and the referenced uploads are written to a manifest so they can be copied
 * into public/.
 *
 *   node scripts/extract-news.mjs <mirror-root> <manifest-out>
 *
 * `mirror-root` is a local copy of www.yahata-sa.co.jp holding the pages as
 * served — save them with plain curl/wget, without link rewriting.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const POSTS = [
  { id: 2037, date: "2026-05-12", label: "2026.05", title: "研修旅行へ行きました" },
  { id: 1682, date: "2025-05-17", label: "2025.05", title: "研修旅行へ行きました" },
  { id: 1397, date: "2024-05-28", label: "2024.05", title: "研修旅行へ行きました！" },
  { id: 1266, date: "2023-09-20", label: "2023.09", title: "天下一合説へ出展してきました！" },
  { id: 1232, date: "2023-08-02", label: "2023.08", title: "ジョブドラフトFes　2023へ出展してきました！" },
  { id: 1057, date: "2023-06-14", label: "2023.06", title: "６０周年記念研修旅行へ行きました" },
  { id: 833, date: "2022-05-16", label: "2022.05", title: "研修旅行へ行って来ました！" },
  { id: 659, date: "2021-10-07", label: "2021.10", title: "ホームページを全面刷新リニューアルしました。" },
  {
    id: 667,
    date: "2021-08-08",
    label: "2021.08",
    title: "サービス部10 月1 日よりエンジンオイルDH-2（現行品）からメガマルチオイルにグレード変更します。"
  },
  { id: 668, date: "2021-08-08", label: "2021.08", title: "車検場ラインテスター設備 老朽化の為更新しました。" }
];

const [, , mirrorRoot = ".", manifestOut = "news-assets.txt"] = process.argv;

const assets = new Set();

function extractBody(html) {
  const match = html.match(/<div class="wp-editor">([\s\S]*?)<\/div>\s*<\/div>\s*<div class="p-news__foot">/);
  if (!match) throw new Error("could not locate the post body");

  return (
    match[1]
      // Responsive variants would multiply the shipped uploads several times over.
      .replace(/\s+srcset="[^"]*"/g, "")
      .replace(/\s+sizes="[^"]*"/g, "")
      .replace(/\s+loading="lazy"/g, "")
      .replace(/https:\/\/www\.yahata-sa\.co\.jp\//g, "/")
      .replace(/src="(\/wp\/[^"]+)"/g, (whole, url) => {
        assets.add(url);
        return whole;
      })
      .replace(/href="(\/wp\/[^"]+)"/g, (whole, url) => {
        assets.add(url);
        return whole;
      })
      .trim()
  );
}

const posts = POSTS.map((post) => ({
  ...post,
  body: extractBody(readFileSync(join(mirrorRoot, "news", String(post.id), "index.html"), "utf8"))
}));

const file = `// Generated by scripts/extract-news.mjs — edit that script, not this file.
export type NewsPost = {
  /** WordPress post id, kept so existing /news/<id>/ links stay valid. */
  id: number;
  /** ISO date used for <time datetime>. */
  date: string;
  /** Year.month label the design shows. */
  label: string;
  title: string;
  /** Editor-authored body markup. */
  body: string;
};

export const news: NewsPost[] = ${JSON.stringify(posts, null, 2)};

export function latestNews(count: number): NewsPost[] {
  return news.slice(0, count);
}

export function findNews(id: number): NewsPost | undefined {
  return news.find((post) => post.id === id);
}
`;

writeFileSync(new URL("../data/news.ts", import.meta.url), file);
writeFileSync(manifestOut, [...assets].sort().join("\n") + "\n");

console.log(`data/news.ts: ${posts.length} posts, ${assets.size} uploads referenced`);
