// Generated by scripts/extract-products.mjs — edit that script, not this file.

/** One built vehicle or option as shown on a term archive page. */
export type ProductVehicle = {
  image: string;
  alt: string;
  name: string;
  /** 特徴 copy; one entry per line. */
  description: string[];
  details: { image: string; captions: string[] }[];
};

/** A taxonomy term — "ウイング車", "床フック" and so on. */
export type ProductTerm = {
  slug: string;
  name: string;
  image: string;
  vehicles: ProductVehicle[];
};

/** Top-level grouping: ボデー or オプション. */
export type ProductCategory = {
  group: string;
  en: string;
  ja: string;
  terms: ProductTerm[];
};

export const productCategories: ProductCategory[] = [
  {
    "group": "body",
    "en": "Body",
    "ja": "ボデー",
    "terms": [
      {
        "slug": "aluminum-block",
        "name": "アルミブロック",
        "image": "/wp/wp-content/uploads/2021/09/cat01_01.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2023/06/6523d9c4c9f718fec2ddf447826d0987-750x563.jpg",
            "alt": "総重量25トンアルミブロック高床車",
            "name": "総重量25トンアルミブロック高床車",
            "description": [
              "3軸髙床アルミブロック3方開式　800×700"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2023/06/86d686019bdaa856d56b682da97c0649-e1686986196690-750x564.jpg",
                "captions": [
                  "リヤ煽埋込式　ステップ取付",
                  "テールランプ上、ステップ付\n（土台フック込）"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2023/06/3949d9c6def895b1eac6f399aabd60a7-750x563.jpg",
                "captions": [
                  "床面、床鉄板張り\n（センターライン付）",
                  "鳥居アルミ縞板張り"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/09/aluminum-block01.jpg",
            "alt": "総重量25トンアルミブロック高床車",
            "name": "総重量25トンアルミブロック高床車",
            "description": [
              "3軸高床アルミブロック5方開式 800×900、荷止め用立柱付"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/09/aluminum-block01_1.jpg",
                "captions": [
                  "リヤーステンレス化粧付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/09/aluminum-block01_2.jpg",
                "captions": [
                  "W/B サイドガード ステンレス製\n丸パイプ4段式"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/09/aluminum-block01_3.jpg",
                "captions": [
                  "W/B右 5方開式 中柱ステンレス\n特注品",
                  "工具箱　FRP製 白 2個取付有"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/09/aluminum-block02.jpg",
            "alt": "総重量25トンアルミブロック高床車",
            "name": "総重量25トンアルミブロック高床車",
            "description": [
              "3軸高床アルミブロック500×500 3方開式",
              "鳥居、土台枠、根太組ステンレス製の耐腐食性に優れた荷台です。"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/09/aluminum-block02_1.jpg",
                "captions": [
                  "ステンレス製鳥居",
                  "ガッチャ掛けR/L",
                  "フタ付物入れ"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/09/aluminum-block02_2.jpg",
                "captions": [
                  "床面 ステンレス製 シマ縞板"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/09/aluminum-block02_3.jpg",
                "captions": [
                  "W/B右 ステンレス 工具箱 2個取付",
                  "サイドガード ステンレス製\n丸パイプ3段式"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/09/aluminum-block03.jpg",
            "alt": "総重量8トンアルミブロック高床車",
            "name": "総重量8トンアルミブロック高床車",
            "description": [
              "総重量8t　6200×2150×700×600"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/09/aluminum-block03_1.jpg",
                "captions": [
                  "リヤー アルミシマ板化粧",
                  "後端物入れ付",
                  "バックアイカメラ埋め込み"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/09/aluminum-block03_2.jpg",
                "captions": [
                  "燃料タンクアルミ製",
                  "ステンレス工具箱付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/09/aluminum-block03_3.jpg",
                "captions": [
                  "サイドガードアルミ製2段式"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "heavy-loads-car",
        "name": "重量物車",
        "image": "/wp/wp-content/uploads/2021/09/cat01_02.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2023/06/c20eb39d0f59a86d06233fd4aefa2103-750x563.jpg",
            "alt": "増トン　クレーン付き重量物車",
            "name": "増トン　クレーン付き重量物車",
            "description": [
              "低床構造式・煽アルミブロック",
              "アルミブロックワイヤー穴付"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2023/06/ce58bfd3aef79828300435a9c79b2d66-750x563.jpg",
                "captions": [
                  "リヤ化粧板式",
                  "歩み板掛け付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2023/06/2f3bd4aa58e6a1675f094d4c4ccfe8a0-e1686986144628-750x680.jpg",
                "captions": [
                  "鳥居アルミ縞板張り"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2023/06/26d998a51256c74edabd713d04a15902-750x563.jpg",
            "alt": "総重量25トンクレーン付重量物車",
            "name": "総重量25トンクレーン付重量物車",
            "description": [
              "3軸低床車　平面交差式",
              "重量物運搬車"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2023/06/5ef76fc393832e8ee9c1fc7f5d6aa8e9-750x563.jpg",
                "captions": [
                  "煽アルミブロック（内側）アルミ縞板張り",
                  "歩み板掛け（ステンレス製）"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2023/06/883b36cd7ee4f3fda92c1d7d5372ee37-750x563.jpg",
                "captions": [
                  "鳥居前、物入れ仕様",
                  "ウインチ付"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body02_01-01.jpg",
            "alt": "総重量20トンクレーン付重量物車",
            "name": "総重量20トンクレーン付重量物車",
            "description": [
              "平面交差式、重量物運搬車、アオリ形状、鉄板煽式"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body02_01-02.jpg",
                "captions": [
                  "W/Bサイドガード丸パイプ(鉄製)クレーン前左右物入付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body02_01-03.jpg",
                "captions": [
                  "リヤーテールランプ埋込化粧板"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body02_01-04.jpg",
                "captions": [
                  "R.O.Hリヤーアウトリガー付クレーン敷板収納庫付"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body02_02-01.jpg",
            "alt": "総重量25トンクレーン付重量物車",
            "name": "総重量25トンクレーン付重量物車",
            "description": [
              "4軸低床車、アオリ3方アルミブロック上辺ALシマ板",
              "リヤーテールナンバープレート埋込式化粧板"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body02_02-02.jpg",
                "captions": [
                  "床鉄板張",
                  "ROHへウインチ埋込有"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body02_02-03.jpg",
                "captions": [
                  "収納式鳥居",
                  "鳥居前R/Lステンレス製物入"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body02_02-04.jpg",
                "captions": [
                  "ROH　アウトリガー付"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body02_03-01.jpg",
            "alt": "総重量25トンクレーン付重量物車",
            "name": "総重量25トンクレーン付重量物車",
            "description": [
              "4軸低床車、アオリ3方アルミブロック上辺ALシマ板",
              "リヤーテールナンバープレート埋込式化粧板"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body02_03-02.jpg",
                "captions": [
                  "リヤーアオリ特殊丁双式",
                  "歩み板掛け"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body02_03-03.jpg",
                "captions": [
                  "鳥居前R/Lウロコステン製物入",
                  "ハイアウトリガー式",
                  "アウトリガ敷板収納底付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body02_03-04.jpg",
                "captions": [
                  "鳥居地下付ウインチ付",
                  "ワイヤー掛 ガッチャ掛け"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "steel-body",
        "name": "鋼材ボデー",
        "image": "/wp/wp-content/uploads/2021/09/cat01_03.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2021/10/body03_01-01.jpg",
            "alt": "総重量25トン規格アオリ車",
            "name": "総重量25トン規格アオリ車",
            "description": [
              "3軸高床5方開式規格アオリ車",
              "サイドガード丸パイプ式3段、R.O.H付"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body03_01-02.jpg",
                "captions": [
                  "コイル立付、シート張用柱付",
                  "床フック埋込、床鉄板張"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body03_01-03.jpg",
                "captions": [
                  "鳥居総鉄板張、埋込フック2個"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body03_01-04.jpg",
                "captions": [
                  "後端物入れ付、バックアイカメラ埋込",
                  "右側丸棒式足掛付、リヤーステップ付"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "scrap",
        "name": "スクラップ",
        "image": "/wp/wp-content/uploads/2021/09/cat01_04.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2021/10/body04_01-01.jpg",
            "alt": "総重量25トンアオリ固定式 スクラップ車",
            "name": "総重量25トンアオリ固定式 スクラップ車",
            "description": [
              "固定アオリ 3方高張力鋼板仕様",
              "差込式ゴミ出口有"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body04_01-02.jpg",
                "captions": [
                  "キャブ上足場台付ボデー直付けシート台"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body04_01-03.jpg",
                "captions": [
                  "マグネット当り止め丸棒式左右足掛"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body04_01-04.jpg",
                "captions": [
                  "リヤー固定式アオリ足掛"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "chip-car",
        "name": "チップ車",
        "image": "/wp/wp-content/uploads/2021/09/cat01_05.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2023/06/7d47c01ef336b92fe9d7ccfebc5b09e3-750x563.jpg",
            "alt": "総重量25トンチップ車",
            "name": "総重量25トンチップ車",
            "description": [
              "バランスボデー式（アルミブロック製）",
              "左右上部アルミブロック固定式"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2023/06/11faf92001f5eb376ec1d5f32163db10-750x563.jpg",
                "captions": [
                  "サイドガード（ステンレス製）",
                  "煽保護材　取付（サイド煽へ取付）"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2023/06/c16c684fa181b809cd42773f542721fa-e1686986649910-750x876.jpg",
                "captions": [
                  "リヤ観音扉式",
                  "棒ハンドル（ステンレス製　W式）"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body05_01-01.jpg",
            "alt": "総重量20トンチップ車",
            "name": "総重量20トンチップ車",
            "description": [
              "アルミブロック製5方開式",
              "サイドガード角パイプ式2段、R.O.H付"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body05_01-02.jpg",
                "captions": [
                  "リヤーアルミブロック製観音扉丁双5対下部開き止め補強付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body05_01-03.jpg",
                "captions": [
                  "固定柱部開き止めパイプ付鳥居右丸棒式足掛5段"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body05_01-04.jpg",
                "captions": [
                  "サイドアオリ、バランスボデー式最上部アオリ固定式"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body05_02-01.jpg",
            "alt": "総重量25トンチップ車",
            "name": "総重量25トンチップ車",
            "description": [
              "3軸高床車アルミブロック製、サイド固定アオリ式",
              "ステンレス製角型シート台付"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body05_02-02.jpg",
                "captions": [
                  "リヤーウロコステンレス製 観音扉式棒ハンドルW2式ステンレス製丁双5対"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body05_02-03.jpg",
                "captions": [
                  "新明和製ダンプ上へアルミブロック製固定アオリ式"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body05_02-04.jpg",
                "captions": [
                  "床新明和製スライドデッキ付開き止め固定丸パイプ2ヵ所"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "drum-can-loading-car",
        "name": "ドラム缶積車",
        "image": "/wp/wp-content/uploads/2021/09/cat01_06.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2023/06/03b532262b85237079640e52a54ddd4f-750x563.jpg",
            "alt": "総重量25トンドラム缶積車",
            "name": "総重量25トンドラム缶積車",
            "description": [
              "バランスボデー式"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2023/07/b0b98ea176316073b6b385c01bfc672b-750x563.jpg",
                "captions": [
                  "上段煽　跳ね上げダンパー"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2023/06/3909a1106cba439c9937912652bdb57d-e1686986008792-750x903.jpg",
                "captions": [
                  "リヤ上段観音扉式",
                  "下段煽（規格品）"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body06_01-01.jpg",
            "alt": "総重量25トンドラム缶積車",
            "name": "総重量25トンドラム缶積車",
            "description": [
              "バランスボデー式　リヤー観音扉（下部アオリ付）7方開式"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body06_01-02.jpg",
                "captions": [
                  "荷台前面上　前出し工作",
                  "キャブ上　導風板付",
                  "キャブベッドレス　タイプ"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body06_01-03.jpg",
                "captions": [
                  "サイド開門状態"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body06_01-04.jpg",
                "captions": [
                  "荷台内部ラッシングレール3段",
                  "床アピトン張"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body06_02-01.jpg",
            "alt": "総重量8トンドラム缶積車",
            "name": "総重量8トンドラム缶積車",
            "description": [
              "積載量　　2950kg",
              "リヤー観音扉式"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body06_02-02.jpg",
                "captions": [
                  "アルミホイール サイドガードアルミ丸パイプ1段式",
                  "リヤーフェンダーアルミ製",
                  "R.O.H　右　物入れ有"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body06_02-03.jpg",
                "captions": [
                  "荷台内部　アルミ製　欄干　　3段式",
                  "幌骨　アルミパイプ製",
                  "欄干　上へ　荷止め　丸棒　R/L付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body06_02-04.jpg",
                "captions": [
                  "リヤーアルミ骨組製　観音扉"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "wing-car",
        "name": "ウイング車",
        "image": "/wp/wp-content/uploads/2021/09/cat01_07.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2021/10/body07_01-01.jpg",
            "alt": "総重量25トンドライウイング車",
            "name": "総重量25トンドライウイング車",
            "description": [
              "4軸低床車により　広大な荷台容積を確保",
              "輸送・荷役効率の向上を追求した高容積ボデー"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body07_01-02.jpg",
                "captions": [
                  "サイドガード　アルミ2段式"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body07_01-03.jpg",
                "captions": [
                  "リヤー観音扉　アルミ型材式"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body07_01-04.jpg",
                "captions": [
                  "内装 羽根内張りベニヤラッシングレール2段式"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "car-with-crane",
        "name": "クレーン付車",
        "image": "/wp/wp-content/uploads/2021/09/cat01_08.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2021/10/body08_01-01.jpg",
            "alt": "総重量25トンクレーン付車",
            "name": "総重量25トンクレーン付車",
            "description": [
              "アオリ 400×400 3方開式",
              "鳥居ガッチャワイヤー収納庫仕様"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_01-02.jpg",
                "captions": [
                  "WB右ステンレス製工具箱付",
                  "アオリ丁双ステンレス"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_01-03.jpg",
                "captions": [
                  "アルミ製サイドガード",
                  "クレーン敷板収納庫付",
                  "鳥居物入左右下部梯子式補強"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_01-04.jpg",
                "captions": [
                  "泥除けゴム1枚物下部ステン付"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body08_02-01.jpg",
            "alt": "総重量20トンクレーン付車",
            "name": "総重量20トンクレーン付車",
            "description": [
              "アオリ アルミブロックR/L 2方開式",
              "鳥居鉄板キャブ側張"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_02-02.jpg",
                "captions": [
                  "ステン丸パイプ製サイドガード物入部開閉式"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_02-03.jpg",
                "captions": [
                  "リヤー歩み掛付化粧板"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_02-04.jpg",
                "captions": [
                  "ハイム丁双"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body08_03-01.jpg",
            "alt": "総重量7.5トンクレーン付車",
            "name": "総重量7.5トンクレーン付車",
            "description": [
              "総重量7.5t メーカー完成ボデー2次架装"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_03-02.jpg",
                "captions": [
                  "リヤー大金丁双式アオリ上辺アルミ縞板"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_03-03.jpg",
                "captions": [
                  "ワイヤー穴4対鳥居アルミ縞板張り"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_03-04.jpg",
                "captions": [
                  "床亜鉛鉄板t 2.3張り"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body08_04-01.jpg",
            "alt": "総重量25トンクレーン付車",
            "name": "総重量25トンクレーン付車",
            "description": [
              "4軸低床車セルフクレーン付、ウインチ付、リヤー歩み板掛付、化粧",
              "板仕様。重量物の積み下ろし等も柔軟に対応。",
              "アオリアルミブロック（上面Alシマ板貼）"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_04-02.jpg",
                "captions": [
                  "リヤー歩み板掛付化粧板",
                  "リヤーアオリ特殊丁双"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_04-03.jpg",
                "captions": [
                  "セルフクレーン付",
                  "鳥居前R/Lステンレス製物入れ付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_04-04.jpg",
                "captions": [
                  "サイドガードステンレス製",
                  "直引ウインチ付",
                  "アオリ丁双ステンレス製"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body08_05-01.jpg",
            "alt": "増トン クレーン付車",
            "name": "増トン クレーン付車",
            "description": [
              "増トン車　アオリ3方アルミブロック",
              "リヤーステンレス製化粧"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_05-02.jpg",
                "captions": [
                  "土台へバックアイカメラ埋込",
                  "ナンバープレート中央"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_05-03.jpg",
                "captions": [
                  "サイドガードアルミ製3段",
                  "鳥居前R/Lミガキステン製物入"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body08_05-04.jpg",
                "captions": [
                  "ROH両フタ式物入",
                  "リヤー泥除けゴム黒色下部ステンレス"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "car-with-self",
        "name": "セルフ付車",
        "image": "/wp/wp-content/uploads/2021/09/cat01_09.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2021/10/body09_01-01.jpg",
            "alt": "総重量25トンセルフ付車",
            "name": "総重量25トンセルフ付車",
            "description": [
              "3軸低床セルフ付フラットボデー"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body09_01-02.jpg",
                "captions": [
                  "リヤーセルフ合わせ化粧板",
                  "リヤー歩み板掛付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body09_01-03.jpg",
                "captions": [
                  "床面 アピトン導板 R/L"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body09_01-04.jpg",
                "captions": [
                  "鳥居セルフ一体化",
                  "直引きウインチ付"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body09_02-01.jpg",
            "alt": "総重量25トン自動歩み付セルフ車",
            "name": "総重量25トン自動歩み付セルフ車",
            "description": [
              "4軸低床セルフ付フラットボデー",
              "荷台全幅自動歩み付"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body09_02-02.jpg",
                "captions": [
                  "セルフ作動自動歩みセット状態"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body09_02-03.jpg",
                "captions": [
                  "鳥居物入収納庫付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body09_02-04.jpg",
                "captions": [
                  "直引ウインチ有"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "semi-trailer",
        "name": "セミトレーラ",
        "image": "/wp/wp-content/uploads/2021/09/cat01_10.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2021/10/body10_01-01.jpg",
            "alt": "最大積載量27,400kg段落ち式低床3軸セミトレーラ",
            "name": "最大積載量27,400kg段落ち式低床3軸セミトレーラ",
            "description": [
              "落ちから後ろ荷台内寸10.5メートル",
              "1軸、3軸　リフトアップ、床面地上高890mm"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body10_01-02.jpg",
                "captions": [
                  "段落ち式"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body10_01-03.jpg",
                "captions": [
                  "段落ち式低床3軸セミトレーラ"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body10_01-04.jpg",
                "captions": [
                  "床フック、コイル立、立柱、ツイストロック付"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body10_02-01.jpg",
            "alt": "最大積載量29,000kg積10メートルセミトレーラ",
            "name": "最大積載量29,000kg積10メートルセミトレーラ",
            "description": [
              "エアサス ディスクブレーキ、1軸、3軸　リフトアップ"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body10_02-02.jpg",
                "captions": [
                  "脱着式ステンレス製シート台付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body10_02-03.jpg",
                "captions": [
                  "リヤーフレーム間テールランプ台ステンレスミガキ化粧"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body10_02-04.jpg",
                "captions": [
                  "3軸アルミホイール、FRP製工具箱"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "tractor",
        "name": "トラクター",
        "image": "/wp/wp-content/uploads/2021/09/cat01_11.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2023/06/5b97df5b8774f031c7e6df9d10f02219-750x563.jpg",
            "alt": "スカニア2デフトラクター",
            "name": "スカニア2デフトラクター",
            "description": [
              "デッキアルミ縞板張り"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2023/06/4adfe0cddf16737855e16fdf814f7472-750x563.jpg",
                "captions": [
                  "デッキ上、物入　製作（特注品）",
                  "作業灯　取付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2023/06/562806d3c90d95a15f318e78c68b05f1-750x563.jpg",
                "captions": [
                  "後方アルミ縞板張り",
                  "アルミ縞板リヤフェンダー（特注品）"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body11_01-01.jpg",
            "alt": "スカニア2デフトラクター",
            "name": "スカニア2デフトラクター",
            "description": [
              "スカニア 2デフトラクターデッキ上特注物入製作"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body11_01-02.jpg",
                "captions": [
                  "デッキアルミ縞板張り",
                  "ステンレス製特注物入"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body11_01-03.jpg",
                "captions": [
                  "作業灯取付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body11_01-04.jpg",
                "captions": [
                  "ステンレス製特注物入"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body11_02-01.jpg",
            "alt": "スカニア2デフトラクター",
            "name": "スカニア2デフトラクター",
            "description": [
              "スカニア 2デフトラクターデッキ上特注物入製作"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body11_02-02.jpg",
                "captions": [
                  "物入上回転灯取付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body11_02-03.jpg",
                "captions": [
                  "物入サイド開閉式フタ付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body11_02-04.jpg",
                "captions": [
                  "物入フタ防水仕様"
                ]
              }
            ]
          }
        ]
      },
      {
        "slug": "other-body",
        "name": "その他",
        "image": "/wp/wp-content/uploads/2021/09/cat01_12.jpg",
        "vehicles": [
          {
            "image": "/wp/wp-content/uploads/2023/06/63e4a9579823ee858f61610e8272cfab-e1686986915421-750x483.jpg",
            "alt": "総重量25トン牧草積高床車",
            "name": "総重量25トン牧草積高床車",
            "description": [
              "バランスボデー式"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2023/06/d6f1a65c40e0286d3647eaf1442e0f7b-750x563.jpg",
                "captions": [
                  "2段折れ煽（アルミブロック製）"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2023/06/4ed4ee1896560e914f05e88bd741e241-750x563.jpg",
                "captions": [
                  "サイドガードステンレスパイプ",
                  "工具箱（ステンレス製　２個）"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2023/06/372618d70f6b659c8c0171d9d35497f0-e1686987022430-750x856.jpg",
                "captions": [
                  "後煽　固定式（ステンレス製）",
                  "フレーム間、ステンレス張り",
                  "車高灯　取付"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body12_01-01.jpg",
            "alt": "総重量22トン原木積車",
            "name": "総重量22トン原木積車",
            "description": [
              "原木積用、ヨーロッパ製アルミスタンション、",
              "ROHパルフィンガークレーン付"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body12_01-02.jpg",
                "captions": [
                  "ROH原木積み専用クレーン付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body12_01-03.jpg",
                "captions": [
                  "リヤーステンレス製化粧板"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body12_01-04.jpg",
                "captions": [
                  "原木積み用立柱アルミ製"
                ]
              }
            ]
          },
          {
            "image": "/wp/wp-content/uploads/2021/10/body12_02-01.jpg",
            "alt": "総重量25トンアコーディオン車",
            "name": "総重量25トンアコーディオン車",
            "description": [
              "アコーディオン シート色　グリーン",
              "4軸低床車、シート収納前後可能",
              "天井クレーンでの荷物の積み下ろしが容易です。"
            ],
            "details": [
              {
                "image": "/wp/wp-content/uploads/2021/10/body12_02-02.jpg",
                "captions": [
                  "リヤー ウロコステンレス製化粧",
                  "アコーディオン振れ止め付"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body12_02-03.jpg",
                "captions": [
                  "アコーディオン前方へ収納"
                ]
              },
              {
                "image": "/wp/wp-content/uploads/2021/10/body12_02-04.jpg",
                "captions": [
                  "床板アピトン仕上げ張り",
                  "床フック、センターフック付"
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "group": "option",
    "en": "Option",
    "ja": "オプション",
    "terms": [
      {
        "slug": "seat-stand",
        "name": "シート台",
        "image": "/wp/wp-content/uploads/2021/09/cat02_01.jpg",
        "vehicles": []
      },
      {
        "slug": "crane-front-storage",
        "name": "クレーン前物入れ",
        "image": "/wp/wp-content/uploads/2021/09/cat02_02.jpg",
        "vehicles": []
      },
      {
        "slug": "product-case",
        "name": "製作物物入れ",
        "image": "/wp/wp-content/uploads/2021/09/cat02_03.jpg",
        "vehicles": []
      },
      {
        "slug": "torii-storage",
        "name": "鳥居物入れ仕様",
        "image": "/wp/wp-content/uploads/2021/09/cat02_04.jpg",
        "vehicles": []
      },
      {
        "slug": "floor-hook",
        "name": "床フック",
        "image": "/wp/wp-content/uploads/2021/09/cat02_05.jpg",
        "vehicles": []
      },
      {
        "slug": "side-guard",
        "name": "サイドガード",
        "image": "/wp/wp-content/uploads/2021/09/cat02_06.jpg",
        "vehicles": []
      },
      {
        "slug": "hinge",
        "name": "丁双",
        "image": "/wp/wp-content/uploads/2021/09/cat02_07.jpg",
        "vehicles": []
      },
      {
        "slug": "lamp-related",
        "name": "ランプ関係",
        "image": "/wp/wp-content/uploads/2021/09/cat02_08.jpg",
        "vehicles": []
      },
      {
        "slug": "tool-box",
        "name": "工具箱（既製品）",
        "image": "/wp/wp-content/uploads/2021/09/cat02_09.jpg",
        "vehicles": []
      },
      {
        "slug": "other-option",
        "name": "その他",
        "image": "/wp/wp-content/uploads/2021/09/cat02_10.jpg",
        "vehicles": []
      }
    ]
  }
];

export function findTerm(group: string, slug: string) {
  const category = productCategories.find((item) => item.group === group);
  const term = category?.terms.find((item) => item.slug === slug);
  return category && term ? { category, term } : undefined;
}
